name:                Bank-Simulation
version:             0.1.0.0
github:              "ShuaibKunji/Bank-Simulation"
license:             BSD3
author:              "Shuaib Sabir Kunji"
maintainer:          "shuaibkunji@gmail.com"
copyright:           "2021 Shuaib Sabir Kunji"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ShuaibKunji/Bank-Simulation#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules: Sim
  other-modules: Lib

executables:
  Bank-Simulation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Bank-Simulation

tests:
  Bank-Simulation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Bank-Simulation
